Insert Into sys_tributacao_icms values ('00', 'Tributada integralmente', 0);                                                                      
Insert Into sys_tributacao_icms values ('10', 'Tributada e com cobrança de ICMS por substituição tributária', 0);                                 
Insert Into sys_tributacao_icms values ('20', 'Com redução de base de cálculo', 0);                                                               
Insert Into sys_tributacao_icms values ('30', 'Isenta ou não tributada e com cobrança de ICMS por substituição tributária', 0);                   
Insert Into sys_tributacao_icms values ('40', 'Isenta', 0);                                                                                       
Insert Into sys_tributacao_icms values ('41', 'Não tributada', 0);                                                                                
Insert Into sys_tributacao_icms values ('50', 'Suspensão', 0);                                                                                    
Insert Into sys_tributacao_icms values ('51', 'Diferimento', 0);                                                                                  
Insert Into sys_tributacao_icms values ('60', 'ICMS cobrado anteriormente por substituição tributária', 0);                                       
Insert Into sys_tributacao_icms values ('70', 'Com redução de base de cálculo e cobrança de ICMS por substituição tributária', 0);                
Insert Into sys_tributacao_icms values ('90', 'Outras', 0);                                                                                       
Insert Into sys_tributacao_icms values ('101', 'Tributada pelo Simples Nacional com permissão de crédito.', 1);                                   
Insert Into sys_tributacao_icms values ('102', 'Tributada pelo Simples Nacional sem permissão de crédito.', 1);                                   
Insert Into sys_tributacao_icms values ('103', 'Isenção do ICMS no Simples Nacional para faixa de receita bruta.', 1);                            
Insert Into sys_tributacao_icms values ('201', 'Tributada pelo SN com permissão de crédito e com cobrança do ICMS por Subst. Trib.', 1);          
Insert Into sys_tributacao_icms values ('202', 'Tributada pelo SN sem permissão de crédito e com cobrança do ICMS por Subst. Trib.', 1);          
Insert Into sys_tributacao_icms values ('203', 'Isenção do ICMS nos SN para faixa de receita bruta e com cobrança do ICMS por Subst. Trib.', 1);  
Insert Into sys_tributacao_icms values ('300', 'Imune', 1);                                                                                       
Insert Into sys_tributacao_icms values ('400', 'Não tributada pelo Simples Nacional.', 1);                                                        
Insert Into sys_tributacao_icms values ('500', 'ICMS cobrado anteriormente por substituição tributária (substituído) ou por antecipação.', 1);    
Insert Into sys_tributacao_icms values ('900', 'Outros', 1);                                                                                      