Insert Into sys_tributacao_pis values ('01', 'Operação Tributável com Alíquota Básica', 0);                                                                                          
Insert Into sys_tributacao_pis values ('02', 'Operação Tributável com Alíquota Diferenciada', 1);                                                                                    
Insert Into sys_tributacao_pis values ('03', 'Operação Tributável com Alíquota por Unidade de Medida de Produto', 2);                                                                
Insert Into sys_tributacao_pis values ('04', 'Operação Tributável Monofásica - Revenda a Alíquota Zero', 3);                                                                         
Insert Into sys_tributacao_pis values ('05', 'Operação Tributável por Substituição Tributária', 4);                                                                                  
Insert Into sys_tributacao_pis values ('06', 'Operação Tributável a Alíquota Zero', 5);                                                                                              
Insert Into sys_tributacao_pis values ('07', 'Operação Isenta da Contribuição', 6);                                                                                                  
Insert Into sys_tributacao_pis values ('08', 'Operação sem Incidênc ia da Contribuição', 7);                                                                                         
Insert Into sys_tributacao_pis values ('09', 'Operação com Suspensão da Contribuição', 8);                                                                                           
Insert Into sys_tributacao_pis values ('49', 'Outras Operações de Saída', 9);                                                                                                        
Insert Into sys_tributacao_pis values ('50', 'Operação com Direito a Crédito - Vinculada Exclusivamente a Receita Tributada no Mercado Interno', 10);                                
Insert Into sys_tributacao_pis values ('51', 'Operação com Direito a Crédito - Vinculada Exclusivamente a Receita Não Tributada no Mercado Interno', 11);                            
Insert Into sys_tributacao_pis values ('52', 'Operação com Direito a Crédito - Vinculada Exclusivamente a Receita de Exportação', 12);                                               
Insert Into sys_tributacao_pis values ('53', 'Operação com Direito a Crédito - Vinculada a Receitas Tributadas e Não-Tributadas no Mercado Interno', 13);                            
Insert Into sys_tributacao_pis values ('54', 'Operação com Direito a Crédito - Vinculada a Receitas Tributadas no Mercado Interno e de Exportação', 14);                             
Insert Into sys_tributacao_pis values ('55', 'Operação com Direito a Crédito - Vinculada a Receitas Não-Tributadas no Mercado Interno e de Exportação', 15);                         
Insert Into sys_tributacao_pis values ('56', 'Operação com Direito a Crédito - Vinculada a Receitas Tributadas e Não-Tributadas no Mercado Interno, e de Exportação', 16);           
Insert Into sys_tributacao_pis values ('60', 'Crédito Presumido - Operação de Aquisição Vinculada Exclusivamente a Receita Tributada no Mercado Interno', 17);                       
Insert Into sys_tributacao_pis values ('61', 'Crédito Presumido - Operação de Aquisição Vinculada Exclusivamente a Receita Não-Tributada no Mercado Interno', 18);                   
Insert Into sys_tributacao_pis values ('62', 'Crédito Presumido - Operação de Aquisição Vinculada Exclusivamente a Receita de Exportação', 19);                                      
Insert Into sys_tributacao_pis values ('63', 'Crédito Presumido - Operação de Aquisição Vinculada a Receitas Tributadas e Não-Tributadas no Mercado Interno', 20);                   
Insert Into sys_tributacao_pis values ('64', 'Crédito Presumido - Operação de Aquisição Vinculada a Receitas Tributadas no Mercado Interno e de Exportação', 21);                    
Insert Into sys_tributacao_pis values ('65', 'Crédito Presumido - Operação de Aquisição Vinculada a Receitas Não-Tributadas no Mercado Interno e de Exportação', 22);                
Insert Into sys_tributacao_pis values ('66', 'Crédito Presumido - Operação de Aquisição Vinculada a Receitas Tributadas e Não-Tributadas no Mercado Interno, e de Exportação', 23);  
Insert Into sys_tributacao_pis values ('67', 'Crédito Presumido - Outras Operações', 24);                                                                                            
Insert Into sys_tributacao_pis values ('70', 'Operação de Aquisição sem Direito a Crédito', 25);                                                                                     
Insert Into sys_tributacao_pis values ('71', 'Operação de Aquisição com Isenção', 26);                                                                                               
Insert Into sys_tributacao_pis values ('72', 'Operação de Aquisição com Suspensão', 27);                                                                                             
Insert Into sys_tributacao_pis values ('73', 'Operação de Aquisição a Alíquota Zero', 28);                                                                                           
Insert Into sys_tributacao_pis values ('74', 'Operação de Aquisição sem Incidência da Contribuição', 29);                                                                            
Insert Into sys_tributacao_pis values ('75', 'Operação de Aquisição por Substituição Tributária', 30);                                                                               
Insert Into sys_tributacao_pis values ('98', 'Outras Operações de Entrada', 31);                                                                                                     
Insert Into sys_tributacao_pis values ('99', 'Outras Operações', 32);                                                                                                                