Insert Into sys_pais values ('00132', 'AFEGANISTAO', null);                                       
Insert Into sys_pais values ('00175', 'ALBANIA, REPUBLICA  DA', null);                            
Insert Into sys_pais values ('00230', 'ALEMANHA', null);                                          
Insert Into sys_pais values ('00310', 'BURKINA FASO', null);                                      
Insert Into sys_pais values ('00370', 'ANDORRA', null);                                           
Insert Into sys_pais values ('00400', 'ANGOLA', null);                                            
Insert Into sys_pais values ('00418', 'ANGUILLA', null);                                          
Insert Into sys_pais values ('00434', 'ANTIGUA E BARBUDA', null);                                 
Insert Into sys_pais values ('00477', 'ANTILHAS HOLANDESAS', null);                               
Insert Into sys_pais values ('00531', 'ARABIA SAUDITA', null);                                    
Insert Into sys_pais values ('00590', 'ARGELIA', null);                                           
Insert Into sys_pais values ('00639', 'ARGENTINA', null);                                         
Insert Into sys_pais values ('00647', 'ARMENIA, REPUBLICA DA', null);                             
Insert Into sys_pais values ('00655', 'ARUBA', null);                                             
Insert Into sys_pais values ('00698', 'AUSTRALIA', null);                                         
Insert Into sys_pais values ('00728', 'AUSTRIA', null);                                           
Insert Into sys_pais values ('00736', 'AZERBAIJAO, REPUBLICA DO', null);                          
Insert Into sys_pais values ('00779', 'BAHAMAS, ILHAS', null);                                    
Insert Into sys_pais values ('00809', 'BAHREIN, ILHAS', null);                                    
Insert Into sys_pais values ('00817', 'BANGLADESH', null);                                        
Insert Into sys_pais values ('00833', 'BARBADOS', null);                                          
Insert Into sys_pais values ('00850', 'BELARUS, REPUBLICA DA', null);                             
Insert Into sys_pais values ('00876', 'BELGICA', null);                                           
Insert Into sys_pais values ('00884', 'BELIZE', null);                                            
Insert Into sys_pais values ('00906', 'BERMUDAS', null);                                          
Insert Into sys_pais values ('00930', 'MIANMAR (BIRMANIA)', null);                                
Insert Into sys_pais values ('00973', 'BOLIVIA, ESTADO PLURINACIONAL DA', null);                  
Insert Into sys_pais values ('00981', 'BOSNIA-HERZEGOVINA (REPUBLICA DA)', null);                 
Insert Into sys_pais values ('01015', 'BOTSUANA', null);                                          
Insert Into sys_pais values ('01058', 'BRASIL', null);                                            
Insert Into sys_pais values ('01082', 'BRUNEI', null);                                            
Insert Into sys_pais values ('01112', 'BULGARIA, REPUBLICA DA', null);                            
Insert Into sys_pais values ('01155', 'BURUNDI', null);                                           
Insert Into sys_pais values ('01198', 'BUTAO', null);                                             
Insert Into sys_pais values ('01279', 'CABO VERDE, REPUBLICA DE', null);                          
Insert Into sys_pais values ('01376', 'CAYMAN, ILHAS', null);                                     
Insert Into sys_pais values ('01414', 'CAMBOJA', null);                                           
Insert Into sys_pais values ('01457', 'CAMAROES', null);                                          
Insert Into sys_pais values ('01490', 'CANADA', null);                                            
Insert Into sys_pais values ('01504', 'GUERNSEY, ILHA DO CANAL (INCLUI ALDERNEY E SARK)', null);  
Insert Into sys_pais values ('01508', 'JERSEY, ILHA DO CANAL', null);                             
Insert Into sys_pais values ('01511', 'CANARIAS, ILHAS', null);                                   
Insert Into sys_pais values ('01538', 'CAZAQUISTAO, REPUBLICA DO', null);                         
Insert Into sys_pais values ('01546', 'CATAR', null);                                             
Insert Into sys_pais values ('01589', 'CHILE', null);                                             
Insert Into sys_pais values ('01600', 'CHINA, REPUBLICA POPULAR', null);                          
Insert Into sys_pais values ('01619', 'FORMOSA (TAIWAN)', null);                                  
Insert Into sys_pais values ('01635', 'CHIPRE', null);                                            
Insert Into sys_pais values ('01651', 'COCOS(KEELING),ILHAS', null);                              
Insert Into sys_pais values ('01694', 'COLOMBIA', null);                                          
Insert Into sys_pais values ('01732', 'COMORES, ILHAS', null);                                    
Insert Into sys_pais values ('01775', 'CONGO', null);                                             
Insert Into sys_pais values ('01830', 'COOK, ILHAS', null);                                       
Insert Into sys_pais values ('01872', 'COREIA (DO NORTE), REP.POP.DEMOCRATICA', null);            
Insert Into sys_pais values ('01902', 'COREIA (DO SUL), REPUBLICA DA', null);                     
Insert Into sys_pais values ('01937', 'COSTA DO MARFIM', null);                                   
Insert Into sys_pais values ('01953', 'CROACIA (REPUBLICA DA)', null);                            
Insert Into sys_pais values ('01961', 'COSTA RICA', null);                                        
Insert Into sys_pais values ('01988', 'COVEITE', null);                                           
Insert Into sys_pais values ('01996', 'CUBA', null);                                              
Insert Into sys_pais values ('02291', 'BENIN', null);                                             
Insert Into sys_pais values ('02321', 'DINAMARCA', null);                                         
Insert Into sys_pais values ('02356', 'DOMINICA,ILHA', null);                                     
Insert Into sys_pais values ('02399', 'EQUADOR', null);                                           
Insert Into sys_pais values ('02402', 'EGITO', null);                                             
Insert Into sys_pais values ('02437', 'ERITREIA', null);                                          
Insert Into sys_pais values ('02445', 'EMIRADOS ARABES UNIDOS', null);                            
Insert Into sys_pais values ('02453', 'ESPANHA', null);                                           
Insert Into sys_pais values ('02461', 'ESLOVENIA, REPUBLICA DA', null);                           
Insert Into sys_pais values ('02470', 'ESLOVACA, REPUBLICA', null);                               
Insert Into sys_pais values ('02496', 'ESTADOS UNIDOS', null);                                    
Insert Into sys_pais values ('02518', 'ESTONIA, REPUBLICA DA', null);                             
Insert Into sys_pais values ('02534', 'ETIOPIA', null);                                           
Insert Into sys_pais values ('02550', 'FALKLAND (ILHAS MALVINAS)', null);                         
Insert Into sys_pais values ('02593', 'FEROE, ILHAS', null);                                      
Insert Into sys_pais values ('02674', 'FILIPINAS', null);                                         
Insert Into sys_pais values ('02712', 'FINLANDIA', null);                                         
Insert Into sys_pais values ('02755', 'FRANCA', null);                                            
Insert Into sys_pais values ('02810', 'GABAO', null);                                             
Insert Into sys_pais values ('02852', 'GAMBIA', null);                                            
Insert Into sys_pais values ('02895', 'GANA', null);                                              
Insert Into sys_pais values ('02917', 'GEORGIA, REPUBLICA DA', null);                             
Insert Into sys_pais values ('02933', 'GIBRALTAR', null);                                         
Insert Into sys_pais values ('02976', 'GRANADA', null);                                           
Insert Into sys_pais values ('03018', 'GRECIA', null);                                            
Insert Into sys_pais values ('03050', 'GROENLANDIA', null);                                       
Insert Into sys_pais values ('03093', 'GUADALUPE', null);                                         
Insert Into sys_pais values ('03131', 'GUAM', null);                                              
Insert Into sys_pais values ('03174', 'GUATEMALA', null);                                         
Insert Into sys_pais values ('03255', 'GUIANA FRANCESA', null);                                   
Insert Into sys_pais values ('03298', 'GUINE', null);                                             
Insert Into sys_pais values ('03310', 'GUINE-EQUATORIAL', null);                                  
Insert Into sys_pais values ('03344', 'GUINE-BISSAU', null);                                      
Insert Into sys_pais values ('03379', 'GUIANA', null);                                            
Insert Into sys_pais values ('03417', 'HAITI', null);                                             
Insert Into sys_pais values ('03450', 'HONDURAS', null);                                          
Insert Into sys_pais values ('03514', 'HONG KONG', null);                                         
Insert Into sys_pais values ('03557', 'HUNGRIA, REPUBLICA DA', null);                             
Insert Into sys_pais values ('03573', 'IEMEN', null);                                             
Insert Into sys_pais values ('03595', 'MAN, ILHA DE', null);                                      
Insert Into sys_pais values ('03611', 'INDIA', null);                                             
Insert Into sys_pais values ('03654', 'INDONESIA', null);                                         
Insert Into sys_pais values ('03697', 'IRAQUE', null);                                            
Insert Into sys_pais values ('03727', 'IRA, REPUBLICA ISLAMICA DO', null);                        
Insert Into sys_pais values ('03751', 'IRLANDA', null);                                           
Insert Into sys_pais values ('03794', 'ISLANDIA', null);                                          
Insert Into sys_pais values ('03832', 'ISRAEL', null);                                            
Insert Into sys_pais values ('03867', 'ITALIA', null);                                            
Insert Into sys_pais values ('03913', 'JAMAICA', null);                                           
Insert Into sys_pais values ('03964', 'JOHNSTON, ILHAS', null);                                   
Insert Into sys_pais values ('03999', 'JAPAO', null);                                             
Insert Into sys_pais values ('04030', 'JORDANIA', null);                                          
Insert Into sys_pais values ('04111', 'KIRIBATI', null);                                          
Insert Into sys_pais values ('04200', 'LAOS, REP.POP.DEMOCR.DO', null);                           
Insert Into sys_pais values ('04235', 'LEBUAN,ILHAS', null);                                      
Insert Into sys_pais values ('04260', 'LESOTO', null);                                            
Insert Into sys_pais values ('04278', 'LETONIA, REPUBLICA DA', null);                             
Insert Into sys_pais values ('04316', 'LIBANO', null);                                            
Insert Into sys_pais values ('04340', 'LIBERIA', null);                                           
Insert Into sys_pais values ('04383', 'LIBIA', null);                                             
Insert Into sys_pais values ('04405', 'LIECHTENSTEIN', null);                                     
Insert Into sys_pais values ('04421', 'LITUANIA, REPUBLICA DA', null);                            
Insert Into sys_pais values ('04456', 'LUXEMBURGO', null);                                        
Insert Into sys_pais values ('04472', 'MACAU', null);                                             
Insert Into sys_pais values ('04499', 'MACEDONIA, ANT.REP.IUGOSLAVA', null);                      
Insert Into sys_pais values ('04502', 'MADAGASCAR', null);                                        
Insert Into sys_pais values ('04525', 'MADEIRA, ILHA DA', null);                                  
Insert Into sys_pais values ('04553', 'MALASIA', null);                                           
Insert Into sys_pais values ('04588', 'MALAVI', null);                                            
Insert Into sys_pais values ('04618', 'MALDIVAS', null);                                          
Insert Into sys_pais values ('04642', 'MALI', null);                                              
Insert Into sys_pais values ('04677', 'MALTA', null);                                             
Insert Into sys_pais values ('04723', 'MARIANAS DO NORTE', null);                                 
Insert Into sys_pais values ('04740', 'MARROCOS', null);                                          
Insert Into sys_pais values ('04766', 'MARSHALL,ILHAS', null);                                    
Insert Into sys_pais values ('04774', 'MARTINICA', null);                                         
Insert Into sys_pais values ('04855', 'MAURICIO', null);                                          
Insert Into sys_pais values ('04880', 'MAURITANIA', null);                                        
Insert Into sys_pais values ('04885', 'MAYOTTE (ILHAS FRANCESAS)', null);                         
Insert Into sys_pais values ('04901', 'MIDWAY, ILHAS', null);                                     
Insert Into sys_pais values ('04936', 'MEXICO', null);                                            
Insert Into sys_pais values ('04944', 'MOLDAVIA, REPUBLICA DA', null);                            
Insert Into sys_pais values ('04952', 'MONACO', null);                                            
Insert Into sys_pais values ('04979', 'MONGOLIA', null);                                          
Insert Into sys_pais values ('04985', 'MONTENEGRO', null);                                        
Insert Into sys_pais values ('04995', 'MICRONESIA', null);                                        
Insert Into sys_pais values ('05010', 'MONTSERRAT,ILHAS', null);                                  
Insert Into sys_pais values ('05053', 'MOCAMBIQUE', null);                                        
Insert Into sys_pais values ('05070', 'NAMIBIA', null);                                           
Insert Into sys_pais values ('05088', 'NAURU', null);                                             
Insert Into sys_pais values ('05118', 'CHRISTMAS,ILHA (NAVIDAD)', null);                          
Insert Into sys_pais values ('05177', 'NEPAL', null);                                             
Insert Into sys_pais values ('05215', 'NICARAGUA', null);                                         
Insert Into sys_pais values ('05258', 'NIGER', null);                                             
Insert Into sys_pais values ('05282', 'NIGERIA', null);                                           
Insert Into sys_pais values ('05312', 'NIUE,ILHA', null);                                         
Insert Into sys_pais values ('05355', 'NORFOLK,ILHA', null);                                      
Insert Into sys_pais values ('05380', 'NORUEGA', null);                                           
Insert Into sys_pais values ('05428', 'NOVA CALEDONIA', null);                                    
Insert Into sys_pais values ('05452', 'PAPUA NOVA GUINE', null);                                  
Insert Into sys_pais values ('05487', 'NOVA ZELANDIA', null);                                     
Insert Into sys_pais values ('05517', 'VANUATU', null);                                           
Insert Into sys_pais values ('05568', 'OMA', null);                                               
Insert Into sys_pais values ('05665', 'PACIFICO,ILHAS DO (POSSESSAO DOS EUA)', null);             
Insert Into sys_pais values ('05738', 'PAISES BAIXOS (HOLANDA)', null);                           
Insert Into sys_pais values ('05754', 'PALAU', null);                                             
Insert Into sys_pais values ('05762', 'PAQUISTAO', null);                                         
Insert Into sys_pais values ('05800', 'PANAMA', null);                                            
Insert Into sys_pais values ('05860', 'PARAGUAI', null);                                          
Insert Into sys_pais values ('05894', 'PERU', null);                                              
Insert Into sys_pais values ('05932', 'PITCAIRN,ILHA', null);                                     
Insert Into sys_pais values ('05991', 'POLINESIA FRANCESA', null);                                
Insert Into sys_pais values ('06033', 'POLONIA, REPUBLICA DA', null);                             
Insert Into sys_pais values ('06076', 'PORTUGAL', null);                                          
Insert Into sys_pais values ('06114', 'PORTO RICO', null);                                        
Insert Into sys_pais values ('06238', 'QUENIA', null);                                            
Insert Into sys_pais values ('06254', 'QUIRGUIZ, REPUBLICA', null);                               
Insert Into sys_pais values ('06289', 'REINO UNIDO', null);                                       
Insert Into sys_pais values ('06408', 'REPUBLICA CENTRO-AFRICANA', null);                         
Insert Into sys_pais values ('06475', 'REPUBLICA DOMINICANA', null);                              
Insert Into sys_pais values ('06602', 'REUNIAO, ILHA', null);                                     
Insert Into sys_pais values ('06653', 'ZIMBABUE', null);                                          
Insert Into sys_pais values ('06700', 'ROMENIA', null);                                           
Insert Into sys_pais values ('06750', 'RUANDA', null);                                            
Insert Into sys_pais values ('06769', 'RUSSIA, FEDERACAO DA', null);                              
Insert Into sys_pais values ('06777', 'SALOMAO, ILHAS', null);                                    
Insert Into sys_pais values ('06858', 'SAARA OCIDENTAL', null);                                   
Insert Into sys_pais values ('06874', 'EL SALVADOR', null);                                       
Insert Into sys_pais values ('06904', 'SAMOA', null);                                             
Insert Into sys_pais values ('06912', 'SAMOA AMERICANA', null);                                   
Insert Into sys_pais values ('06955', 'SAO CRISTOVAO E NEVES,ILHAS', null);                       
Insert Into sys_pais values ('06971', 'SAN MARINO', null);                                        
Insert Into sys_pais values ('07005', 'SAO PEDRO E MIQUELON', null);                              
Insert Into sys_pais values ('07056', 'SAO VICENTE E GRANADINAS', null);                          
Insert Into sys_pais values ('07102', 'SANTA HELENA', null);                                      
Insert Into sys_pais values ('07153', 'SANTA LUCIA', null);                                       
Insert Into sys_pais values ('07200', 'SAO TOME E PRINCIPE, ILHAS', null);                        
Insert Into sys_pais values ('07285', 'SENEGAL', null);                                           
Insert Into sys_pais values ('07315', 'SEYCHELLES', null);                                        
Insert Into sys_pais values ('07358', 'SERRA LEOA', null);                                        
Insert Into sys_pais values ('07370', 'SERVIA', null);                                            
Insert Into sys_pais values ('07412', 'CINGAPURA', null);                                         
Insert Into sys_pais values ('07447', 'SIRIA, REPUBLICA ARABE DA', null);                         
Insert Into sys_pais values ('07480', 'SOMALIA', null);                                           
Insert Into sys_pais values ('07501', 'SRI LANKA', null);                                         
Insert Into sys_pais values ('07544', 'SUAZILANDIA', null);                                       
Insert Into sys_pais values ('07560', 'AFRICA DO SUL', null);                                     
Insert Into sys_pais values ('07595', 'SUDAO', null);                                             
Insert Into sys_pais values ('07641', 'SUECIA', null);                                            
Insert Into sys_pais values ('07676', 'SUICA', null);                                             
Insert Into sys_pais values ('07706', 'SURINAME', null);                                          
Insert Into sys_pais values ('07722', 'TADJIQUISTAO, REPUBLICA DO', null);                        
Insert Into sys_pais values ('07765', 'TAILANDIA', null);                                         
Insert Into sys_pais values ('07803', 'TANZANIA, REP.UNIDA DA', null);                            
Insert Into sys_pais values ('07820', 'TERRITORIO BRIT.OC.INDICO', null);                         
Insert Into sys_pais values ('07838', 'DJIBUTI', null);                                           
Insert Into sys_pais values ('07889', 'CHADE', null);                                             
Insert Into sys_pais values ('07919', 'TCHECA, REPUBLICA', null);                                 
Insert Into sys_pais values ('07951', 'TIMOR LESTE', null);                                       
Insert Into sys_pais values ('08001', 'TOGO', null);                                              
Insert Into sys_pais values ('08052', 'TOQUELAU,ILHAS', null);                                    
Insert Into sys_pais values ('08109', 'TONGA', null);                                             
Insert Into sys_pais values ('08150', 'TRINIDAD E TOBAGO', null);                                 
Insert Into sys_pais values ('08206', 'TUNISIA', null);                                           
Insert Into sys_pais values ('08230', 'TURCAS E CAICOS,ILHAS', null);                             
Insert Into sys_pais values ('08249', 'TURCOMENISTAO, REPUBLICA DO', null);                       
Insert Into sys_pais values ('08273', 'TURQUIA', null);                                           
Insert Into sys_pais values ('08281', 'TUVALU', null);                                            
Insert Into sys_pais values ('08311', 'UCRANIA', null);                                           
Insert Into sys_pais values ('08338', 'UGANDA', null);                                            
Insert Into sys_pais values ('08451', 'URUGUAI', null);                                           
Insert Into sys_pais values ('08478', 'UZBEQUISTAO, REPUBLICA DO', null);                         
Insert Into sys_pais values ('08486', 'VATICANO, EST.DA CIDADE DO', null);                        
Insert Into sys_pais values ('08508', 'VENEZUELA', null);                                         
Insert Into sys_pais values ('08583', 'VIETNA', null);                                            
Insert Into sys_pais values ('08630', 'VIRGENS,ILHAS (BRITANICAS)', null);                        
Insert Into sys_pais values ('08664', 'VIRGENS,ILHAS (E.U.A.)', null);                            
Insert Into sys_pais values ('08702', 'FIJI', null);                                              
Insert Into sys_pais values ('08737', 'WAKE, ILHA', null);                                        
Insert Into sys_pais values ('08885', 'CONGO, REPUBLICA DEMOCRATICA DO', null);                   
Insert Into sys_pais values ('08907', 'ZAMBIA', null);                                            