Insert Into str_unidade (und_codigo, und_descricao, und_sigla) values (00, 'Não se aplica', null);           
Insert Into str_unidade (und_codigo, und_descricao, und_sigla) values (01, 'Caixa', 'CX.');           
Insert Into str_unidade (und_codigo, und_descricao, und_sigla) values (02, 'Cartela', NULL);          
Insert Into str_unidade (und_codigo, und_descricao, und_sigla) values (03, 'Centimetro', 'CM');       
Insert Into str_unidade (und_codigo, und_descricao, und_sigla) values (04, 'Comprimido', 'CMP');      
Insert Into str_unidade (und_codigo, und_descricao, und_sigla) values (05, 'Diaria', 'D');            
Insert Into str_unidade (und_codigo, und_descricao, und_sigla) values (06, 'Doses', 'DS');            
Insert Into str_unidade (und_codigo, und_descricao, und_sigla) values (07, 'Duzia', NULL);            
Insert Into str_unidade (und_codigo, und_descricao, und_sigla) values (08, 'Envelope', 'ENV');        
Insert Into str_unidade (und_codigo, und_descricao, und_sigla) values (09, 'Fardo', 'FD');            
Insert Into str_unidade (und_codigo, und_descricao, und_sigla) values (10, 'Folhas', 'FL');           
Insert Into str_unidade (und_codigo, und_descricao, und_sigla) values (11, 'Frasco', 'F/A');          
Insert Into str_unidade (und_codigo, und_descricao, und_sigla) values (12, 'Galao', NULL);            
Insert Into str_unidade (und_codigo, und_descricao, und_sigla) values (13, 'Garrafa', 'GRF');         
Insert Into str_unidade (und_codigo, und_descricao, und_sigla) values (14, 'Gramas', 'GR');           
Insert Into str_unidade (und_codigo, und_descricao, und_sigla) values (15, 'Haste', 'HASTE');         
Insert Into str_unidade (und_codigo, und_descricao, und_sigla) values (16, 'Hora', 'H');              
Insert Into str_unidade (und_codigo, und_descricao, und_sigla) values (17, 'Jogo', NULL);             
Insert Into str_unidade (und_codigo, und_descricao, und_sigla) values (18, 'Kilograma', 'KG');        
Insert Into str_unidade (und_codigo, und_descricao, und_sigla) values (19, 'Kit', NULL);              
Insert Into str_unidade (und_codigo, und_descricao, und_sigla) values (20, 'Lata', 'LAT');            
Insert Into str_unidade (und_codigo, und_descricao, und_sigla) values (21, 'Litro', NULL);            
Insert Into str_unidade (und_codigo, und_descricao, und_sigla) values (22, 'Mes', 'M');               
Insert Into str_unidade (und_codigo, und_descricao, und_sigla) values (23, 'Metro', 'MT');            
Insert Into str_unidade (und_codigo, und_descricao, und_sigla) values (24, 'Metro cubico', 'M³');    
Insert Into str_unidade (und_codigo, und_descricao, und_sigla) values (25, 'Metro quadrado', 'M²');  
Insert Into str_unidade (und_codigo, und_descricao, und_sigla) values (26, 'Mililitro', 'ML');        
Insert Into str_unidade (und_codigo, und_descricao, und_sigla) values (27, 'Pacote', 'PCT');          
Insert Into str_unidade (und_codigo, und_descricao, und_sigla) values (28, 'Pares', NULL);            
Insert Into str_unidade (und_codigo, und_descricao, und_sigla) values (29, 'Peca', 'PC');             
Insert Into str_unidade (und_codigo, und_descricao, und_sigla) values (30, 'Peso/Peso', 'P/P');       
Insert Into str_unidade (und_codigo, und_descricao, und_sigla) values (31, 'Resma', 'RESMA');         
Insert Into str_unidade (und_codigo, und_descricao, und_sigla) values (32, 'Rolos', 'RL');            
Insert Into str_unidade (und_codigo, und_descricao, und_sigla) values (33, 'Saco', NULL);             
Insert Into str_unidade (und_codigo, und_descricao, und_sigla) values (34, 'Unidade', 'UND');         